name: Heracles Microservice
on: 
  workflow_dispatch:
    inputs:
      heracles_alias:
        description: 'Heracles Alias'     
        required: true
env:
   HERACLES_PAT: ${{ secrets.GITHUB_TOKEN }}
   HERACLES_ALIAS: ${{ github.event.inputs.heracles_alias }}  
jobs:
  job1:
    name: Build Heracles Container and push to ACR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{env.HERACLES_ALIAS}}acr.azurecr.io
        username: ${{env.HERACLES_ALIAS}}acr
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build -f heracles/Dockerfile -t ${{env.HERACLES_ALIAS}}acr.azurecr.io/heracles/heracles:${{github.run_number}} .
        docker push ${{env.HERACLES_ALIAS}}acr.azurecr.io/heracles/heracles:${{github.run_number}}
  job2:
    name: Associate Heracles container with function app
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{env.HERACLES_ALIAS}}acr.azurecr.io
        username: ${{env.HERACLES_ALIAS}}acr
        password: ${{ secrets.ACR_PASSWORD }}

    - id: step1
      name: Set Function App Docker Image
      shell: bash
      run: |
        az functionapp config container set --docker-custom-image-name ${{env.HERACLES_ALIAS}}acr.azurecr.io/heracles/heracles:${{github.run_number}} \
             --docker-registry-server-password ${{secrets.ACR_PASSWORD }} \
             --docker-registry-server-url https://${{env.HERACLES_ALIAS}}acr.azurecr.io \
             --docker-registry-server-user ${{env.HERACLES_ALIAS}}acr \
             --name ${{env.HERACLES_ALIAS}}-gen-func \
             --resource-group ${{env.HERACLES_ALIAS}}-rg

        az webapp log config --docker-container-logging filesystem \
             --name ${{env.HERACLES_ALIAS}}-gen-func \
             --resource-group ${{env.HERACLES_ALIAS}}-rg